server:
  port: 8082
spring:
  application:
    name: webflux-mongodb
  data:
    mongodb:
      authentication-database: usersdb
      username: dev1234
      password: dev1234
      database: usersdb
      port: 27017
      host: 127.0.0.1
    #uri: mongodb://dev1234:dev1234@localhost:27017/usersdb
management:
  health:
    diskspace:
      enabled: false
    mongo:
      enabled: true
    ping:
      enabled: false
  endpoint:
    health:
      show-details: always
